name: 📋 Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DATABASE_URL: postgres://postgres:postgres@eggsauce_db:5432/eggsauce
    strategy:
      matrix:
        python-version: [3.12]
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
            pytest
